/**
 * Adhkaar Library Dataset
 * Sources: Fazail-e-Amaal, Hisnul Muslim, Sahih al-Bukhari,
 *          Sahih Muslim, Abu Dawood, Jami' at-Tirmidhi
 */
import { Dhikr, Routine } from './types';

export const ADHKAAR_LIBRARY: Dhikr[] = [
  {
    id: 'subhanallah',
    nameEn: 'SubhanAllah',
    nameAr: 'سُبْحَانَ ٱللَّٰهِ',
    transliteration: 'Subḥāna-llāh',
    meaning: 'Glory be to Allah',
    benefits: 'Among the most beloved words to Allah. Plants a palm tree in Jannah for the one who recites it.',
    reference: 'Sahih Muslim 2731',
    sourceBook: 'Sahih Muslim',
    targetCount: 33,
    category: ['daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['tasbih', 'after-salah', 'jannah'],
    isSystem: true,
  },
  {
    id: 'alhamdulillah',
    nameEn: 'Alhamdulillah',
    nameAr: 'ٱلْحَمْدُ لِلَّٰهِ',
    transliteration: 'Al-ḥamdu lillāh',
    meaning: 'All praise belongs to Allah',
    benefits: 'Fills the scales of good deeds. The Prophet ﷺ said it fills what is between the heavens and the earth.',
    reference: 'Sahih Muslim 223',
    sourceBook: 'Sahih Muslim',
    targetCount: 33,
    category: ['daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['tasbih', 'after-salah', 'mizan'],
    isSystem: true,
  },
  {
    id: 'allahuakbar',
    nameEn: 'Allahu Akbar',
    nameAr: 'ٱللَّٰهُ أَكْبَرُ',
    transliteration: 'Allāhu Akbar',
    meaning: 'Allah is the Greatest',
    benefits: 'Fills what is between the heavens and the earth. Among the four most beloved words to Allah.',
    reference: 'Sahih Muslim 2137',
    sourceBook: 'Sahih Muslim',
    targetCount: 34,
    category: ['daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['tasbih', 'after-salah', 'takbir'],
    isSystem: true,
  },
  {
    id: 'subhanallahi-wa-bihamdihi',
    nameEn: 'SubhanAllahi wa Bihamdihi',
    nameAr: 'سُبْحَانَ ٱللَّٰهِ وَبِحَمْدِهِ',
    transliteration: 'Subḥāna-llāhi wa biḥamdih',
    meaning: 'Glory be to Allah and praise belongs to Him',
    benefits: 'Whoever says it 100 times a day, his sins are forgiven even if they are like the foam of the sea.',
    reference: 'Sahih al-Bukhari 6405, Sahih Muslim 2691',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 100,
    category: ['daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['tasbih', 'forgiveness', 'sins'],
    isSystem: true,
  },
  {
    id: 'astaghfirullah',
    nameEn: 'Astaghfirullah',
    nameAr: 'أَسْتَغْفِرُ ٱللَّٰهَ',
    transliteration: 'Astaghfiru-llāh',
    meaning: 'I seek forgiveness from Allah',
    benefits: 'The Prophet ﷺ sought forgiveness more than 70 times a day. Opens doors of provision and relief.',
    reference: 'Sahih al-Bukhari 6307',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 100,
    category: ['istighfar', 'daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['forgiveness', 'tawbah', 'rizq'],
    isSystem: true,
  },
  {
    id: 'la-ilaha-illa-allah-wahdahu',
    nameEn: 'La ilaha illa Allah wahdahu',
    nameAr: 'لَا إِلَٰهَ إِلَّا ٱللَّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ ٱلْمُلْكُ وَلَهُ ٱلْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Lā ilāha illa-llāhu waḥdahu lā sharīka lah, lahu-l-mulku wa lahu-l-ḥamdu wa huwa ʿalā kulli shayʾin qadīr',
    meaning: 'There is no god but Allah alone, with no partner. To Him belongs all dominion and praise, and He is over all things capable.',
    benefits: 'Whoever says it 100 times has the reward of freeing 10 slaves, 100 good deeds written, 100 bad deeds erased, and protection from Shaytan.',
    reference: 'Sahih al-Bukhari 3293, Sahih Muslim 2691',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 100,
    category: ['daily', 'morning', 'evening', 'protection'],
    time: 'morning',
    isFeatured: true,
    difficulty: 'medium',
    tags: ['tahlil', 'protection', 'forgiveness', 'jannah'],
    isSystem: true,
  },
  {
    id: 'sayyidul-istighfar',
    nameEn: 'Sayyidul Istighfar',
    nameAr: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: "Allāhumma anta rabbī lā ilāha illā ant, khalaqtanī wa anā ʿabduk, wa anā ʿalā ʿahdika wa waʿdika ma-staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abūʾu laka bi-niʿmatika ʿalayy, wa abūʾu bi-dhanbī, fa-ghfir lī fa-innahu lā yaghfiru-dh-dhunūba illā ant",
    meaning: "O Allah, You are my Lord. There is no god but You. You created me and I am Your servant. I am upon Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your blessing upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.",
    benefits: 'The Master of Seeking Forgiveness. Whoever says it with conviction in the morning and dies that day before evening enters Paradise. Same for evening.',
    reference: 'Sahih al-Bukhari 6306',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 1,
    category: ['istighfar', 'morning', 'evening'],
    time: 'morning',
    isFeatured: true,
    difficulty: 'long',
    tags: ['forgiveness', 'morning-adhkar', 'evening-adhkar', 'jannah'],
    isSystem: true,
  },
  {
    id: 'ayatul-kursi',
    nameEn: 'Ayatul Kursi',
    nameAr: 'ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۚ لَا تَأْخُذُهُۥ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ',
    transliteration: "Allāhu lā ilāha illā huwa-l-ḥayyu-l-qayyūm, lā taʾkhudhuhū sinatun wa lā nawm...",
    meaning: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep...',
    benefits: 'Whoever recites it after every obligatory prayer, nothing prevents him from entering Jannah except death. Protects from Shaytan when recited before sleep.',
    reference: 'Sahih al-Bukhari 5010, Surah Al-Baqarah 2:255',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 1,
    category: ['protection', 'morning', 'evening', 'quranic', 'sleep'],
    time: 'after-salah',
    isFeatured: true,
    difficulty: 'medium',
    tags: ['quran', 'protection', 'after-salah', 'sleep', 'jannah'],
    isSystem: true,
  },
  {
    id: 'surah-ikhlas',
    nameEn: 'Surah Al-Ikhlas',
    nameAr: 'قُلْ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ',
    transliteration: 'Qul huwa-llāhu aḥad, Allāhu-ṣ-ṣamad, lam yalid wa lam yūlad, wa lam yakun lahu kufuwan aḥad',
    meaning: 'Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent.',
    benefits: 'Reciting it once equals one-third of the Quran. Reciting it 3 times equals reciting the entire Quran.',
    reference: 'Sahih al-Bukhari 5013',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 3,
    category: ['quranic', 'morning', 'evening', 'protection', 'sleep'],
    time: 'morning',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['quran', 'morning-adhkar', 'evening-adhkar', 'sleep', '3-quls'],
    isSystem: true,
  },
  {
    id: 'surah-falaq',
    nameEn: 'Surah Al-Falaq',
    nameAr: 'قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    transliteration: 'Qul aʿūdhu bi-rabb il-falaq, min sharri mā khalaq, wa min sharri ghāsiqin idhā waqab, wa min sharri-n-naffāthāti fi-l-ʿuqad, wa min sharri ḥāsidin idhā ḥasad',
    meaning: 'Say: I seek refuge in the Lord of daybreak, from the evil of that which He created, from the evil of darkness when it settles, from the evil of those who blow on knots, and from the evil of an envier when he envies.',
    benefits: 'Protection from evil, black magic, envy and harm. The Prophet ﷺ recited the 3 Quls every morning and evening 3 times.',
    reference: 'Sunan Abu Dawood 5082, Sahih al-Bukhari 5017',
    sourceBook: 'Abu Dawood',
    targetCount: 3,
    category: ['quranic', 'morning', 'evening', 'protection', 'sleep'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['quran', 'protection', 'morning-adhkar', '3-quls', 'ruqyah'],
    isSystem: true,
  },
  {
    id: 'surah-naas',
    nameEn: 'Surah An-Naas',
    nameAr: 'قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ ۝ مَلِكِ ٱلنَّاسِ ۝ إِلَٰهِ ٱلنَّاسِ ۝ مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ ۝ ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ۝ مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ',
    transliteration: 'Qul aʿūdhu bi-rabb in-nās, maliki-n-nās, ilāhi-n-nās, min sharri-l-waswāsi-l-khannās, alladhī yuwaswisu fī ṣudūri-n-nās, mina-l-jinnati wa-n-nās',
    meaning: 'Say: I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer, who whispers in the hearts of mankind, from among the jinn and mankind.',
    benefits: 'Protection from whisperings of Shaytan and evil from jinn and humans. Completes the 3 Quls for morning/evening protection.',
    reference: 'Sunan Abu Dawood 5082',
    sourceBook: 'Abu Dawood',
    targetCount: 3,
    category: ['quranic', 'morning', 'evening', 'protection', 'sleep'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['quran', 'protection', 'morning-adhkar', '3-quls', 'ruqyah'],
    isSystem: true,
  },
  {
    id: 'hasbiyallahu',
    nameEn: 'HasbiyAllahu la ilaha illa Huwa',
    nameAr: 'حَسْبِيَ ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ ٱلْعَرْشِ ٱلْعَظِيمِ',
    transliteration: 'Ḥasbiya-llāhu lā ilāha illā huwa, ʿalayhi tawakkaltu wa huwa rabb ul-ʿarshi-l-ʿaẓīm',
    meaning: 'Allah is sufficient for me. There is no god but Him. Upon Him I rely and He is the Lord of the Mighty Throne.',
    benefits: 'Whoever says it 7 times morning and evening, Allah will suffice him in whatever worries him of this world and the Hereafter.',
    reference: 'Sunan Abu Dawood 5081',
    sourceBook: 'Abu Dawood',
    targetCount: 7,
    category: ['morning', 'evening', 'protection', 'motivation'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['morning-adhkar', 'evening-adhkar', 'tawakkul', 'protection'],
    isSystem: true,
  },
  {
    id: 'bismillahilladhi',
    nameEn: 'Bismillahilladhi la yadurru',
    nameAr: 'بِسْمِ ٱللَّهِ ٱلَّذِي لَا يَضُرُّ مَعَ ٱسْمِهِ شَيْءٌ فِي ٱلْأَرْضِ وَلَا فِي ٱلسَّمَاءِ وَهُوَ ٱلسَّمِيعُ ٱلْعَلِيمُ',
    transliteration: "Bismi-llāhi-lladhī lā yaḍurru maʿa-smihi shayʾun fi-l-arḍi wa lā fi-s-samāʾi wa huwa-s-samīʿu-l-ʿalīm",
    meaning: 'In the name of Allah, with Whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, All-Knowing.',
    benefits: 'Whoever says it 3 times in the morning and evening, nothing will harm him.',
    reference: 'Sunan Abu Dawood 5088, Jami at-Tirmidhi 3388',
    sourceBook: 'Abu Dawood',
    targetCount: 3,
    category: ['morning', 'evening', 'protection'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['morning-adhkar', 'evening-adhkar', 'protection', 'harm'],
    isSystem: true,
  },
  {
    id: 'radheetu-billahi',
    nameEn: 'Radheetu billahi Rabba',
    nameAr: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالإِسْلامِ دِينًا، وَبِمُحَمَّدٍ نَبِيًّا',
    transliteration: "Raḍītu bi-llāhi rabbā, wa bi-l-islāmi dīnā, wa bi-Muḥammadin nabiyyā",
    meaning: 'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad ﷺ as my Prophet.',
    benefits: 'Whoever says it 3 times in the morning and evening, it is a right upon Allah to please him on the Day of Judgement.',
    reference: 'Sunan Abu Dawood 5072, Jami at-Tirmidhi 3389',
    sourceBook: 'Abu Dawood',
    targetCount: 3,
    category: ['morning', 'evening', 'motivation'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['morning-adhkar', 'evening-adhkar', 'iman', 'contentment'],
    isSystem: true,
  },
  {
    id: 'darood-ibrahim',
    nameEn: 'Darood Ibrahim',
    nameAr: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ',
    transliteration: "Allāhumma ṣalli ʿalā Muḥammad wa ʿalā āli Muḥammad, kamā ṣallayta ʿalā Ibrāhīm wa ʿalā āli Ibrāhīm, innaka ḥamīdun majīd. Allāhumma bārik ʿalā Muḥammad wa ʿalā āli Muḥammad, kamā bārakta ʿalā Ibrāhīm wa ʿalā āli Ibrāhīm, innaka ḥamīdun majīd",
    meaning: 'O Allah, send Your blessings upon Muhammad and the family of Muhammad, as You sent blessings upon Ibrahim and the family of Ibrahim. Verily You are Full of Praise, Full of Glory. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim. Verily You are Full of Praise, Full of Glory.',
    benefits: 'For every Salawat sent upon the Prophet ﷺ, Allah sends 10 blessings upon the person, erases 10 sins, and raises him 10 ranks.',
    reference: 'Sahih al-Bukhari 3370, Sahih Muslim 406',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 10,
    category: ['salawat', 'daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'long',
    tags: ['salawat', 'darood', 'prophet', 'blessings'],
    isSystem: true,
  },
  {
    id: 'lailahaillallah',
    nameEn: 'La ilaha illa Allah',
    nameAr: 'لَا إِلَٰهَ إِلَّا ٱللَّٰهُ',
    transliteration: 'Lā ilāha illa-llāh',
    meaning: 'There is no god but Allah',
    benefits: 'The best of dhikr. Renews faith. The Prophet ﷺ said: "Renew your faith" — meaning say La ilaha illa Allah.',
    reference: 'Musnad Ahmad, Hisnul Muslim',
    sourceBook: 'Hisnul Muslim',
    targetCount: 100,
    category: ['daily', 'morning', 'evening', 'motivation'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['tahlil', 'iman', 'faith'],
    isSystem: true,
  },

  // ─── Daily Life Duas ────────────────────────────────────────────────────────

  {
    id: 'dua-waking-up',
    nameEn: 'Dua on Waking Up',
    nameAr: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: 'Alḥamdu lillāhi-lladhī aḥyānā baʿda mā amātanā wa ilayhi-n-nushūr',
    meaning: 'All praise is for Allah who gave us life after having taken it from us, and unto Him is the resurrection.',
    benefits: 'The Prophet ﷺ recited this every morning upon waking. It reminds us that each new day is a gift from Allah.',
    reference: 'Sahih al-Bukhari 6312',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 1,
    category: ['morning', 'daily'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['morning-adhkar', 'waking-up', 'daily-life'],
    isSystem: true,
  },
  {
    id: 'dua-entering-home',
    nameEn: 'Dua on Entering Home',
    nameAr: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا',
    transliteration: "Allāhumma innī asʾaluka khayra-l-mawlaji wa khayra-l-makhraji, bismi-llāhi walajnā, wa bismi-llāhi kharajnā, wa ʿalā-llāhi rabbanā tawakkalnā",
    meaning: 'O Allah, I ask You for the good of entering and the good of leaving. In the name of Allah we enter, and in the name of Allah we leave, and upon our Lord we put our trust.',
    benefits: 'Reciting this when entering the home brings blessings and protects the home from evil.',
    reference: 'Sunan Abu Dawood 5096',
    sourceBook: 'Abu Dawood',
    targetCount: 1,
    category: ['daily', 'protection'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'long',
    tags: ['daily-life', 'home', 'protection', 'entering'],
    isSystem: true,
  },
  {
    id: 'dua-leaving-home',
    nameEn: 'Dua on Leaving Home',
    nameAr: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'Bismi-llāhi tawakkaltu ʿalā-llāhi wa lā ḥawla wa lā quwwata illā billāh',
    meaning: 'In the name of Allah, I place my trust in Allah, and there is no might or power except with Allah.',
    benefits: 'Whoever says this upon leaving home will be guided, protected, and Shaytan will move away from him.',
    reference: 'Sunan Abu Dawood 5095, Jami at-Tirmidhi 3426',
    sourceBook: 'Abu Dawood',
    targetCount: 1,
    category: ['daily', 'protection', 'morning'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'medium',
    tags: ['daily-life', 'leaving-home', 'tawakkul', 'protection'],
    isSystem: true,
  },
  {
    id: 'dua-before-eating',
    nameEn: 'Dua Before Eating',
    nameAr: 'بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ',
    transliteration: 'Bismi-llāhi wa ʿalā barakati-llāh',
    meaning: 'In the name of Allah and with the blessings of Allah.',
    benefits: 'The Prophet ﷺ commanded this before eating. If forgotten, say: Bismi-llāhi awwalahu wa ākhirahu.',
    reference: 'Sunan Abu Dawood 3767',
    sourceBook: 'Abu Dawood',
    targetCount: 1,
    category: ['daily'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['daily-life', 'eating', 'bismillah'],
    isSystem: true,
  },
  {
    id: 'dua-after-eating',
    nameEn: 'Dua After Eating',
    nameAr: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    transliteration: "Alḥamdu lillāhi-lladhī aṭʿamanā wa saqānā wa jaʿalanā muslimīn",
    meaning: 'All praise is for Allah who fed us and gave us drink and made us Muslims.',
    benefits: 'Expressing gratitude to Allah after eating earns reward and keeps blessings in the food.',
    reference: 'Sunan Abu Dawood 3850',
    sourceBook: 'Abu Dawood',
    targetCount: 1,
    category: ['daily'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['daily-life', 'eating', 'gratitude'],
    isSystem: true,
  },
  {
    id: 'dua-before-sleeping',
    nameEn: 'Dua Before Sleeping',
    nameAr: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismikal-lāhumma amūtu wa aḥyā',
    meaning: 'In Your name, O Allah, I die and I live.',
    benefits: 'The Prophet ﷺ said this every night before sleeping. Sleep is a minor death and waking is a new life.',
    reference: 'Sahih al-Bukhari 6324',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 1,
    category: ['sleep', 'evening'],
    time: 'sleep',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['sleep', 'night', 'evening-adhkar'],
    isSystem: true,
  },
  {
    id: 'dua-after-wudu',
    nameEn: 'Dua After Wudu',
    nameAr: 'أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',
    transliteration: "Ashhadu an lā ilāha illā-llāhu waḥdahu lā sharīka lah, wa ashhadu anna Muḥammadan ʿabduhu wa rasūluh",
    meaning: 'I bear witness that there is no god but Allah alone with no partner, and I bear witness that Muhammad is His servant and messenger.',
    benefits: 'The eight gates of Jannah will be opened and one may enter through whichever they wish.',
    reference: 'Sahih Muslim 234',
    sourceBook: 'Sahih Muslim',
    targetCount: 1,
    category: ['daily', 'morning'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'medium',
    tags: ['wudu', 'purification', 'jannah', 'shahada'],
    isSystem: true,
  },
  {
    id: 'dua-entering-masjid',
    nameEn: 'Dua on Entering Masjid',
    nameAr: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    transliteration: 'Allāhumma-ftaḥ lī abwāba raḥmatik',
    meaning: 'O Allah, open for me the gates of Your mercy.',
    benefits: 'Seeking Allah\'s mercy when entering His house — a beautiful way to begin worship.',
    reference: 'Sahih Muslim 713',
    sourceBook: 'Sahih Muslim',
    targetCount: 1,
    category: ['daily', 'morning'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['masjid', 'mosque', 'daily-life', 'mercy'],
    isSystem: true,
  },
  {
    id: 'dua-leaving-masjid',
    nameEn: 'Dua on Leaving Masjid',
    nameAr: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    transliteration: 'Allāhumma innī asʾaluka min faḍlik',
    meaning: 'O Allah, I ask You of Your bounty.',
    benefits: 'Asking for Allah\'s provision and bounty when leaving the masjid — going back to the world with His blessing.',
    reference: 'Sahih Muslim 713',
    sourceBook: 'Sahih Muslim',
    targetCount: 1,
    category: ['daily'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['masjid', 'mosque', 'daily-life', 'rizq'],
    isSystem: true,
  },

  // ─── Travel Duas ─────────────────────────────────────────────────────────────

  {
    id: 'dua-travel',
    nameEn: 'Dua for Travelling',
    nameAr: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنقَلِبُونَ',
    transliteration: "Subḥāna-lladhī sakhkhara lanā hādhā wa mā kunnā lahu muqrinīn, wa innā ilā rabbinā la-munqalibūn",
    meaning: 'Glory be to He who has subjected this for us, and we were not capable of doing it ourselves. And indeed, to our Lord we will surely return.',
    benefits: 'This is the sunnah dua for mounting or beginning a journey. Keeps the traveller protected.',
    reference: 'Sahih Muslim 1342',
    sourceBook: 'Sahih Muslim',
    targetCount: 1,
    category: ['daily', 'protection'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['travel', 'journey', 'protection', 'daily-life'],
    isSystem: true,
  },
  {
    id: 'dua-rain',
    nameEn: 'Dua on Seeing Rain',
    nameAr: 'اللَّهُمَّ صَيِّبًا نَافِعًا',
    transliteration: 'Allāhumma ṣayyiban nāfiʿā',
    meaning: 'O Allah, make it a beneficial rain.',
    benefits: 'The time of rain is a time when duas are accepted. This was the supplication of the Prophet ﷺ when it rained.',
    reference: 'Sahih al-Bukhari 1032',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 1,
    category: ['daily', 'motivation'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['rain', 'daily-life', 'dua-accepted'],
    isSystem: true,
  },

  // ─── Forgiveness & Repentance ────────────────────────────────────────────────

  {
    id: 'astaghfirullah-full',
    nameEn: 'Istighfar (Full)',
    nameAr: 'أَسْتَغْفِرُ اللَّهَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ',
    transliteration: "Astaghfiru-llāha-lladhī lā ilāha illā huwa-l-ḥayyu-l-qayyūmu wa atūbu ilayh",
    meaning: 'I seek forgiveness from Allah — there is no god but He, the Ever-Living, the Sustainer — and I repent to Him.',
    benefits: 'Sins are forgiven even if numerous as the foam of the sea for the one who says this.',
    reference: 'Sunan Abu Dawood 1517',
    sourceBook: 'Abu Dawood',
    targetCount: 3,
    category: ['istighfar', 'daily'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'medium',
    tags: ['forgiveness', 'tawbah', 'istighfar'],
    isSystem: true,
  },
  {
    id: 'dua-anxiety',
    nameEn: 'Dua for Anxiety & Grief',
    nameAr: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
    transliteration: "Allāhumma innī aʿūdhu bika mina-l-hammi wa-l-ḥazan, wa-l-ʿajzi wa-l-kasal, wa-l-bukhli wa-l-jubn, wa ḍalaʿi-d-dayn wa ghalabati-r-rijāl",
    meaning: 'O Allah, I seek refuge in You from anxiety and grief, from weakness and laziness, from miserliness and cowardice, from the burden of debt and from being overpowered by men.',
    benefits: 'The Prophet ﷺ taught this dua for overcoming anxiety, worry, debt, and feelings of helplessness.',
    reference: 'Sahih al-Bukhari 6369',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 1,
    category: ['motivation', 'istighfar', 'protection'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'long',
    tags: ['anxiety', 'grief', 'stress', 'mental-health', 'protection'],
    isSystem: true,
  },
  {
    id: 'dua-debt',
    nameEn: 'Dua for Debt Relief',
    nameAr: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    transliteration: "Allāhumma-kfinī biḥalālika ʿan ḥarāmik, wa aghnini bifaḍlika ʿamman siwāk",
    meaning: 'O Allah, suffice me with what You have made lawful against what You have made unlawful, and make me self-sufficient with Your grace from depending on anyone other than You.',
    benefits: 'The Prophet ﷺ said: if one had debt as great as a mountain and said this, Allah would pay it off.',
    reference: 'Jami at-Tirmidhi 3563',
    sourceBook: 'Jami at-Tirmidhi',
    targetCount: 1,
    category: ['motivation', 'daily'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['debt', 'rizq', 'provision', 'motivation'],
    isSystem: true,
  },

  // ─── Protection & Ruqyah ─────────────────────────────────────────────────────

  {
    id: 'dua-evil-eye',
    nameEn: 'Protection from Evil Eye',
    nameAr: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ',
    transliteration: "Aʿūdhu bi-kalimāti-llāhi-t-tāmmati min kulli shayṭānin wa hāmmatin wa min kulli ʿaynin lāmmah",
    meaning: 'I seek refuge in the perfect words of Allah from every devil and poisonous creature and from every evil eye.',
    benefits: 'The Prophet ﷺ used to seek protection for Hasan and Husain with these words. Protects from jinn and evil eye.',
    reference: 'Sahih al-Bukhari 3371',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 3,
    category: ['protection', 'evening', 'sleep'],
    time: 'evening',
    isFeatured: true,
    difficulty: 'medium',
    tags: ['evil-eye', 'protection', 'ruqyah', 'children'],
    isSystem: true,
  },
  {
    id: 'dua-sihr',
    nameEn: 'Protection from Black Magic',
    nameAr: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: "Bismi-llāhi-lladhī lā yaḍurru maʿa-smihi shayʾun fi-l-arḍi wa lā fi-s-samāʾi wa huwa-s-samīʿu-l-ʿalīm",
    meaning: 'In the name of Allah, with whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, All-Knowing.',
    benefits: 'Whoever says this 3 times in the morning and evening will not be harmed by anything.',
    reference: 'Sunan Abu Dawood 5088',
    sourceBook: 'Abu Dawood',
    targetCount: 3,
    category: ['protection', 'morning', 'evening'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['protection', 'ruqyah', 'morning-adhkar', 'evening-adhkar'],
    isSystem: true,
  },
  {
    id: 'ayat-shifa',
    nameEn: 'Ayat of Healing',
    nameAr: 'وَيَشْفِ صُدُورَ قَوْمٍ مُّؤْمِنِينَ',
    transliteration: "Wa yashfi ṣudūra qawmin muʾminīn",
    meaning: 'And heal the breasts of a believing people.',
    benefits: 'Part of the 6 healing verses of the Quran used for ruqyah. Recite over water and drink for healing.',
    reference: 'Quran 9:14',
    sourceBook: 'Quran',
    targetCount: 7,
    category: ['quranic', 'protection'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['healing', 'shifa', 'ruqyah', 'quran'],
    isSystem: true,
  },

  // ─── Family & Children ───────────────────────────────────────────────────────

  {
    id: 'dua-good-spouse',
    nameEn: 'Dua for a Righteous Spouse & Family',
    nameAr: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
    transliteration: "Rabbanā hab lanā min azwājinā wa dhurriyyātinā qurrata aʿyunin wa-jʿalnā lil-muttaqīna imāmā",
    meaning: 'Our Lord, grant us from among our wives and offspring comfort to our eyes and make us a leader for the righteous.',
    benefits: 'A quranic dua for a blessed family life. The slaves of Ar-Rahman are described as those who make this dua.',
    reference: 'Quran 25:74',
    sourceBook: 'Quran',
    targetCount: 1,
    category: ['quranic', 'motivation', 'daily'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'medium',
    tags: ['family', 'marriage', 'children', 'quran', 'home'],
    isSystem: true,
  },
  {
    id: 'dua-parents',
    nameEn: 'Dua for Parents',
    nameAr: 'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    transliteration: 'Rabb ir-ḥamhumā kamā rabbayānī ṣaghīrā',
    meaning: 'My Lord, have mercy upon them as they raised me when I was small.',
    benefits: 'This quranic dua for parents earns immense reward. Making dua for parents is one of the acts that benefits them after death.',
    reference: 'Quran 17:24',
    sourceBook: 'Quran',
    targetCount: 1,
    category: ['quranic', 'daily', 'motivation'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['parents', 'family', 'quran', 'mercy'],
    isSystem: true,
  },

  // ─── Knowledge & Success ─────────────────────────────────────────────────────

  {
    id: 'dua-knowledge',
    nameEn: 'Dua for Knowledge',
    nameAr: 'رَبِّ زِدْنِي عِلْمًا',
    transliteration: 'Rabb zidnī ʿilmā',
    meaning: 'My Lord, increase me in knowledge.',
    benefits: 'A short but powerful quranic dua. The Prophet ﷺ was never told to seek more of anything except knowledge.',
    reference: 'Quran 20:114',
    sourceBook: 'Quran',
    targetCount: 3,
    category: ['quranic', 'motivation', 'daily'],
    time: 'morning',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['knowledge', 'ilm', 'quran', 'study'],
    isSystem: true,
  },
  {
    id: 'dua-exam-difficulty',
    nameEn: 'Dua in Times of Difficulty',
    nameAr: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: 'Ḥasbuna-llāhu wa niʿma-l-wakīl',
    meaning: 'Allah is sufficient for us and He is the best Disposer of affairs.',
    benefits: 'When Ibrahim (AS) was thrown into the fire, and when the Prophet ﷺ faced the enemy at Uhud — both said this. Allah sufficed them.',
    reference: 'Sahih al-Bukhari 4563, Quran 3:173',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 7,
    category: ['quranic', 'motivation', 'protection', 'morning'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['difficulty', 'tawakkul', 'hardship', 'quran', 'motivation'],
    isSystem: true,
  },
  {
    id: 'dua-good-deed',
    nameEn: 'Dua for Acceptance of Deeds',
    nameAr: 'رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Rabbanā taqabbal minnā innaka anta-s-samīʿu-l-ʿalīm',
    meaning: 'Our Lord, accept from us. Indeed, You are the All-Hearing, the All-Knowing.',
    benefits: 'The dua of Ibrahim and Ismail (AS) while building the Kaaba. The best dua to make after every good deed.',
    reference: 'Quran 2:127',
    sourceBook: 'Quran',
    targetCount: 1,
    category: ['quranic', 'daily', 'motivation'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['acceptance', 'deeds', 'quran', 'ibadah'],
    isSystem: true,
  },

  // ─── Salah-Related ───────────────────────────────────────────────────────────

  {
    id: 'dua-istikhara',
    nameEn: 'Dua al-Istikhara',
    nameAr: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ وَتَعْلَمُ وَلَا أَعْلَمُ وَأَنْتَ عَلَّامُ الْغُيُوبِ',
    transliteration: "Allāhumma innī astakhīruka biʿilmika wa astaqdiruka biqudratika wa asʾaluka min faḍlika-l-ʿaẓīm, fa-innaka taqdiru wa lā aqdiru, wa taʿlamu wa lā aʿlamu, wa anta ʿallāmu-l-ghuyūb",
    meaning: 'O Allah, I seek Your guidance by Your knowledge, and seek Your ability by Your power, and ask of Your great bounty. For You are able and I am not, and You know and I do not, and You are the Knower of the unseen.',
    benefits: 'Prayed in 2 rakats before any major decision. Allah then makes the matter easy if good for you, and removes it if not.',
    reference: 'Sahih al-Bukhari 1166',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 1,
    category: ['daily', 'motivation'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'long',
    tags: ['istikhara', 'decision', 'guidance', 'prayer'],
    isSystem: true,
  },
  {
    id: 'dua-witr',
    nameEn: 'Dua al-Qunoot (Witr)',
    nameAr: 'اللَّهُمَّ اهْدِنَا فِيمَنْ هَدَيْتَ وَعَافِنَا فِيمَنْ عَافَيْتَ وَتَوَلَّنَا فِيمَنْ تَوَلَّيْتَ وَبَارِكْ لَنَا فِيمَا أَعْطَيْتَ وَقِنَا شَرَّ مَا قَضَيْتَ',
    transliteration: "Allāhumma-hdinā fīman hadayt, wa ʿāfinā fīman ʿāfayt, wa tawallanā fīman tawallayt, wa bārik lanā fīmā aʿṭayt, wa qinā sharra mā qaḍayt",
    meaning: 'O Allah, guide us among those You have guided, pardon us among those You have pardoned, be our ally among those You have allied, bless what You have bestowed upon us, and protect us from the evil of what You have decreed.',
    benefits: 'The complete Dua al-Qunoot for Witr prayer. A comprehensive supplication covering guidance, health, and protection.',
    reference: 'Sunan Abu Dawood 1425',
    sourceBook: 'Abu Dawood',
    targetCount: 1,
    category: ['daily', 'motivation', 'protection'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'long',
    tags: ['qunoot', 'witr', 'prayer', 'comprehensive'],
    isSystem: true,
  },

  // ─── Salawat Variations ──────────────────────────────────────────────────────

  {
    id: 'salawat-short',
    nameEn: 'Salawat (Short)',
    nameAr: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ',
    transliteration: 'Allāhumma ṣalli ʿalā Muḥammad',
    meaning: 'O Allah, send blessings upon Muhammad.',
    benefits: 'For every single salawat, Allah sends 10 blessings, erases 10 sins, and raises you 10 ranks.',
    reference: 'Sahih Muslim 408',
    sourceBook: 'Sahih Muslim',
    targetCount: 100,
    category: ['salawat', 'daily'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['salawat', 'prophet', 'short', 'easy'],
    isSystem: true,
  },
  {
    id: 'salawat-friday',
    nameEn: 'Salawat on Friday',
    nameAr: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ',
    transliteration: 'Allāhumma ṣalli ʿalā Muḥammadin wa ʿalā āli Muḥammad',
    meaning: 'O Allah, send Your blessings upon Muhammad and upon the family of Muhammad.',
    benefits: 'Friday is the best day of the week. Sending abundant Salawat on Friday is a sunnah strongly encouraged.',
    reference: 'Sunan Abu Dawood 1047',
    sourceBook: 'Abu Dawood',
    targetCount: 1000,
    category: ['salawat', 'daily'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['salawat', 'friday', 'jumu\'ah', 'prophet'],
    isSystem: true,
  },

  // ─── Quranic Duas ────────────────────────────────────────────────────────────

  {
    id: 'dua-musa',
    nameEn: "Dua of Musa (AS)",
    nameAr: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي',
    transliteration: 'Rabb ishraḥ lī ṣadrī wa yassir lī amrī',
    meaning: 'My Lord, expand for me my chest and ease for me my task.',
    benefits: 'The dua of Prophet Musa (AS) before facing Pharaoh. Perfect for before any difficult task or speech.',
    reference: 'Quran 20:25-26',
    sourceBook: 'Quran',
    targetCount: 1,
    category: ['quranic', 'motivation', 'daily'],
    time: 'morning',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['quran', 'musa', 'ease', 'courage', 'public-speaking'],
    isSystem: true,
  },
  {
    id: 'dua-yunus',
    nameEn: "Dua of Yunus (AS)",
    nameAr: 'لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ',
    transliteration: 'Lā ilāha illā anta subḥānaka innī kuntu mina-ẓ-ẓālimīn',
    meaning: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
    benefits: 'Allah says no Muslim says this in any matter except that Allah answers him. Yunus (AS) was rescued from the whale\'s belly with this dua.',
    reference: 'Quran 21:87, Jami at-Tirmidhi 3505',
    sourceBook: 'Jami at-Tirmidhi',
    targetCount: 40,
    category: ['quranic', 'istighfar', 'motivation', 'protection'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['quran', 'yunus', 'distress', 'answered-dua', 'tawbah'],
    isSystem: true,
  },
  {
    id: 'dua-ayyub',
    nameEn: "Dua of Ayyub (AS)",
    nameAr: 'أَنِّي مَسَّنِيَ الضُّرُّ وَأَنتَ أَرْحَمُ الرَّاحِمِينَ',
    transliteration: "Annī massaniya-ḍ-ḍurru wa anta arḥamu-r-rāḥimīn",
    meaning: 'Adversity has touched me and you are the Most Merciful of the merciful.',
    benefits: 'Ayyub (AS) was afflicted for 18 years but never complained — he just reminded Allah of his state. Allah immediately answered and cured him.',
    reference: 'Quran 21:83',
    sourceBook: 'Quran',
    targetCount: 1,
    category: ['quranic', 'motivation', 'istighfar'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['quran', 'ayyub', 'illness', 'hardship', 'mercy'],
    isSystem: true,
  },
  {
    id: 'dua-ibrahim-fire',
    nameEn: "Dua of Ibrahim (AS) in the Fire",
    nameAr: 'حَسْبِيَ اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: 'Ḥasbiya-llāhu wa niʿma-l-wakīl',
    meaning: 'Allah is sufficient for me and He is the best Disposer of affairs.',
    benefits: 'Ibrahim (AS) said this when thrown into the fire — and Allah made the fire cool and safe. Complete reliance on Allah in the darkest moments.',
    reference: 'Sahih al-Bukhari 4564',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 7,
    category: ['quranic', 'motivation', 'protection'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['ibrahim', 'tawakkul', 'fire', 'trial', 'quran', 'protection'],
    isSystem: true,
  },
  {
    id: 'dua-jannah',
    nameEn: 'Dua for Jannah',
    nameAr: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: "Rabbanā ātinā fi-d-dunyā ḥasanatan wa fi-l-ākhirati ḥasanatan wa qinā ʿadhāba-n-nār",
    meaning: 'Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.',
    benefits: 'The most comprehensive dua in the Quran. The Prophet ﷺ made this dua most abundantly.',
    reference: 'Sahih al-Bukhari 6389, Quran 2:201',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 3,
    category: ['quranic', 'daily', 'motivation'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'medium',
    tags: ['jannah', 'quran', 'comprehensive', 'dunya', 'akhirah'],
    isSystem: true,
  },
  {
    id: 'last-two-baqarah',
    nameEn: 'Last Two Verses of Al-Baqarah',
    nameAr: 'آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ',
    transliteration: "Āmana-r-rasūlu bimā unzila ilayhi min rabbihi wa-l-muʾminūn, kullun āmana billāhi wa malāʾikatihi wa kutubihi wa rusulihi...",
    meaning: 'The Messenger has believed in what was revealed to him from his Lord, and so have the believers. All of them have believed in Allah, His angels, His books, and His messengers...',
    benefits: 'Whoever recites these two verses at night, they will suffice him. They are a protection for the entire night.',
    reference: 'Sahih al-Bukhari 5009, Quran 2:285-286',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 1,
    category: ['quranic', 'sleep', 'protection', 'evening'],
    time: 'sleep',
    isFeatured: true,
    difficulty: 'long',
    tags: ['quran', 'baqarah', 'sleep', 'protection', 'night'],
    isSystem: true,
  },
];


// Helper: get adhkaar by category
export const getAdhkaarByCategory = (category: string): Dhikr[] =>
  ADHKAAR_LIBRARY.filter((d) => d.category?.includes(category as never));

// Helper: get featured adhkaar
export const getFeaturedAdhkaar = (): Dhikr[] =>
  ADHKAAR_LIBRARY.filter((d) => d.isFeatured);

// Helper: get morning routine (ordered)
export const getMorningRoutine = (): Dhikr[] =>
  ADHKAAR_LIBRARY.filter((d) => d.category?.includes('morning')).slice(0, 6);

// Helper: get evening routine (ordered)
export const getEveningRoutine = (): Dhikr[] =>
  ADHKAAR_LIBRARY.filter((d) => d.category?.includes('evening')).slice(0, 6);

// ─── Default System Routines ────────────────────────────────────────────────

export const DEFAULT_ROUTINES: Routine[] = [
  {
    id: 'routine-morning',
    name: 'Morning Routine',
    emoji: '🌅',
    dhikrIds: [
      'dua-waking-up',
      'astaghfirullah',
      'sayyidul-istighfar',
      'dua-leaving-home',
      'ayatul-kursi',
      'surah-ikhlas',
      'surah-falaq',
      'surah-naas',
      'subhanallah',
      'alhamdulillah',
      'allahuakbar',
      'darood-ibrahim',
    ],
    isSystem: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'routine-evening',
    name: 'Evening Routine',
    emoji: '🌙',
    dhikrIds: [
      'astaghfirullah',
      'ayatul-kursi',
      'surah-ikhlas',
      'surah-falaq',
      'surah-naas',
      'subhanallahi-wa-bihamdihi',
      'dua-evil-eye',
      'last-two-baqarah',
      'dua-before-sleeping',
      'darood-ibrahim',
    ],
    isSystem: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'routine-after-salah',
    name: 'After Salah',
    emoji: '🤲',
    dhikrIds: [
      'subhanallah',
      'alhamdulillah',
      'allahuakbar',
      'ayatul-kursi',
      'dua-good-deed',
      'darood-ibrahim',
    ],
    isSystem: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'routine-sleep',
    name: 'Before Sleep',
    emoji: '😴',
    dhikrIds: [
      'dua-before-sleeping',
      'ayatul-kursi',
      'surah-ikhlas',
      'surah-falaq',
      'surah-naas',
      'last-two-baqarah',
      'dua-evil-eye',
    ],
    isSystem: true,
    createdAt: new Date(0).toISOString(),
  },
];
