/**
 * Adhkaar Library Dataset
 * Sources: Fazail-e-Amaal, Hisnul Muslim, Sahih al-Bukhari,
 *          Sahih Muslim, Abu Dawood, Jami' at-Tirmidhi
 */
import { Dhikr, Routine } from './types';

export const ADHKAAR_LIBRARY: Dhikr[] = [
  {
    id: 'subhanallah',
    nameEn: 'SubhanAllah',
    nameAr: 'سُبْحَانَ ٱللَّٰهِ',
    transliteration: 'Subḥāna-llāh',
    meaning: 'Glory be to Allah',
    benefits: 'Among the most beloved words to Allah. Plants a palm tree in Jannah for the one who recites it.',
    reference: 'Sahih Muslim 2731',
    sourceBook: 'Sahih Muslim',
    targetCount: 33,
    category: ['daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['tasbih', 'after-salah', 'jannah'],
    isSystem: true,
  },
  {
    id: 'alhamdulillah',
    nameEn: 'Alhamdulillah',
    nameAr: 'ٱلْحَمْدُ لِلَّٰهِ',
    transliteration: 'Al-ḥamdu lillāh',
    meaning: 'All praise belongs to Allah',
    benefits: 'Fills the scales of good deeds. The Prophet ﷺ said it fills what is between the heavens and the earth.',
    reference: 'Sahih Muslim 223',
    sourceBook: 'Sahih Muslim',
    targetCount: 33,
    category: ['daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['tasbih', 'after-salah', 'mizan'],
    isSystem: true,
  },
  {
    id: 'allahuakbar',
    nameEn: 'Allahu Akbar',
    nameAr: 'ٱللَّٰهُ أَكْبَرُ',
    transliteration: 'Allāhu Akbar',
    meaning: 'Allah is the Greatest',
    benefits: 'Fills what is between the heavens and the earth. Among the four most beloved words to Allah.',
    reference: 'Sahih Muslim 2137',
    sourceBook: 'Sahih Muslim',
    targetCount: 34,
    category: ['daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['tasbih', 'after-salah', 'takbir'],
    isSystem: true,
  },
  {
    id: 'subhanallahi-wa-bihamdihi',
    nameEn: 'SubhanAllahi wa Bihamdihi',
    nameAr: 'سُبْحَانَ ٱللَّٰهِ وَبِحَمْدِهِ',
    transliteration: 'Subḥāna-llāhi wa biḥamdih',
    meaning: 'Glory be to Allah and praise belongs to Him',
    benefits: 'Whoever says it 100 times a day, his sins are forgiven even if they are like the foam of the sea.',
    reference: 'Sahih al-Bukhari 6405, Sahih Muslim 2691',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 100,
    category: ['daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['tasbih', 'forgiveness', 'sins'],
    isSystem: true,
  },
  {
    id: 'astaghfirullah',
    nameEn: 'Astaghfirullah',
    nameAr: 'أَسْتَغْفِرُ ٱللَّٰهَ',
    transliteration: 'Astaghfiru-llāh',
    meaning: 'I seek forgiveness from Allah',
    benefits: 'The Prophet ﷺ sought forgiveness more than 70 times a day. Opens doors of provision and relief.',
    reference: 'Sahih al-Bukhari 6307',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 100,
    category: ['istighfar', 'daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['forgiveness', 'tawbah', 'rizq'],
    isSystem: true,
  },
  {
    id: 'la-ilaha-illa-allah-wahdahu',
    nameEn: 'La ilaha illa Allah wahdahu',
    nameAr: 'لَا إِلَٰهَ إِلَّا ٱللَّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ ٱلْمُلْكُ وَلَهُ ٱلْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Lā ilāha illa-llāhu waḥdahu lā sharīka lah, lahu-l-mulku wa lahu-l-ḥamdu wa huwa ʿalā kulli shayʾin qadīr',
    meaning: 'There is no god but Allah alone, with no partner. To Him belongs all dominion and praise, and He is over all things capable.',
    benefits: 'Whoever says it 100 times has the reward of freeing 10 slaves, 100 good deeds written, 100 bad deeds erased, and protection from Shaytan.',
    reference: 'Sahih al-Bukhari 3293, Sahih Muslim 2691',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 100,
    category: ['daily', 'morning', 'evening', 'protection'],
    time: 'morning',
    isFeatured: true,
    difficulty: 'medium',
    tags: ['tahlil', 'protection', 'forgiveness', 'jannah'],
    isSystem: true,
  },
  {
    id: 'sayyidul-istighfar',
    nameEn: 'Sayyidul Istighfar',
    nameAr: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: "Allāhumma anta rabbī lā ilāha illā ant, khalaqtanī wa anā ʿabduk, wa anā ʿalā ʿahdika wa waʿdika ma-staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abūʾu laka bi-niʿmatika ʿalayy, wa abūʾu bi-dhanbī, fa-ghfir lī fa-innahu lā yaghfiru-dh-dhunūba illā ant",
    meaning: "O Allah, You are my Lord. There is no god but You. You created me and I am Your servant. I am upon Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your blessing upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.",
    benefits: 'The Master of Seeking Forgiveness. Whoever says it with conviction in the morning and dies that day before evening enters Paradise. Same for evening.',
    reference: 'Sahih al-Bukhari 6306',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 1,
    category: ['istighfar', 'morning', 'evening'],
    time: 'morning',
    isFeatured: true,
    difficulty: 'long',
    tags: ['forgiveness', 'morning-adhkar', 'evening-adhkar', 'jannah'],
    isSystem: true,
  },
  {
    id: 'ayatul-kursi',
    nameEn: 'Ayatul Kursi',
    nameAr: 'ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۚ لَا تَأْخُذُهُۥ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ',
    transliteration: "Allāhu lā ilāha illā huwa-l-ḥayyu-l-qayyūm, lā taʾkhudhuhū sinatun wa lā nawm...",
    meaning: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep...',
    benefits: 'Whoever recites it after every obligatory prayer, nothing prevents him from entering Jannah except death. Protects from Shaytan when recited before sleep.',
    reference: 'Sahih al-Bukhari 5010, Surah Al-Baqarah 2:255',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 1,
    category: ['protection', 'morning', 'evening', 'quranic', 'sleep'],
    time: 'after-salah',
    isFeatured: true,
    difficulty: 'medium',
    tags: ['quran', 'protection', 'after-salah', 'sleep', 'jannah'],
    isSystem: true,
  },
  {
    id: 'surah-ikhlas',
    nameEn: 'Surah Al-Ikhlas',
    nameAr: 'قُلْ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ',
    transliteration: 'Qul huwa-llāhu aḥad, Allāhu-ṣ-ṣamad, lam yalid wa lam yūlad, wa lam yakun lahu kufuwan aḥad',
    meaning: 'Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent.',
    benefits: 'Reciting it once equals one-third of the Quran. Reciting it 3 times equals reciting the entire Quran.',
    reference: 'Sahih al-Bukhari 5013',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 3,
    category: ['quranic', 'morning', 'evening', 'protection', 'sleep'],
    time: 'morning',
    isFeatured: true,
    difficulty: 'easy',
    tags: ['quran', 'morning-adhkar', 'evening-adhkar', 'sleep', '3-quls'],
    isSystem: true,
  },
  {
    id: 'surah-falaq',
    nameEn: 'Surah Al-Falaq',
    nameAr: 'قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    transliteration: 'Qul aʿūdhu bi-rabb il-falaq, min sharri mā khalaq, wa min sharri ghāsiqin idhā waqab, wa min sharri-n-naffāthāti fi-l-ʿuqad, wa min sharri ḥāsidin idhā ḥasad',
    meaning: 'Say: I seek refuge in the Lord of daybreak, from the evil of that which He created, from the evil of darkness when it settles, from the evil of those who blow on knots, and from the evil of an envier when he envies.',
    benefits: 'Protection from evil, black magic, envy and harm. The Prophet ﷺ recited the 3 Quls every morning and evening 3 times.',
    reference: 'Sunan Abu Dawood 5082, Sahih al-Bukhari 5017',
    sourceBook: 'Abu Dawood',
    targetCount: 3,
    category: ['quranic', 'morning', 'evening', 'protection', 'sleep'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['quran', 'protection', 'morning-adhkar', '3-quls', 'ruqyah'],
    isSystem: true,
  },
  {
    id: 'surah-naas',
    nameEn: 'Surah An-Naas',
    nameAr: 'قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ ۝ مَلِكِ ٱلنَّاسِ ۝ إِلَٰهِ ٱلنَّاسِ ۝ مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ ۝ ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ۝ مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ',
    transliteration: 'Qul aʿūdhu bi-rabb in-nās, maliki-n-nās, ilāhi-n-nās, min sharri-l-waswāsi-l-khannās, alladhī yuwaswisu fī ṣudūri-n-nās, mina-l-jinnati wa-n-nās',
    meaning: 'Say: I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer, who whispers in the hearts of mankind, from among the jinn and mankind.',
    benefits: 'Protection from whisperings of Shaytan and evil from jinn and humans. Completes the 3 Quls for morning/evening protection.',
    reference: 'Sunan Abu Dawood 5082',
    sourceBook: 'Abu Dawood',
    targetCount: 3,
    category: ['quranic', 'morning', 'evening', 'protection', 'sleep'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['quran', 'protection', 'morning-adhkar', '3-quls', 'ruqyah'],
    isSystem: true,
  },
  {
    id: 'hasbiyallahu',
    nameEn: 'HasbiyAllahu la ilaha illa Huwa',
    nameAr: 'حَسْبِيَ ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ ٱلْعَرْشِ ٱلْعَظِيمِ',
    transliteration: 'Ḥasbiya-llāhu lā ilāha illā huwa, ʿalayhi tawakkaltu wa huwa rabb ul-ʿarshi-l-ʿaẓīm',
    meaning: 'Allah is sufficient for me. There is no god but Him. Upon Him I rely and He is the Lord of the Mighty Throne.',
    benefits: 'Whoever says it 7 times morning and evening, Allah will suffice him in whatever worries him of this world and the Hereafter.',
    reference: 'Sunan Abu Dawood 5081',
    sourceBook: 'Abu Dawood',
    targetCount: 7,
    category: ['morning', 'evening', 'protection', 'motivation'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['morning-adhkar', 'evening-adhkar', 'tawakkul', 'protection'],
    isSystem: true,
  },
  {
    id: 'bismillahilladhi',
    nameEn: 'Bismillahilladhi la yadurru',
    nameAr: 'بِسْمِ ٱللَّهِ ٱلَّذِي لَا يَضُرُّ مَعَ ٱسْمِهِ شَيْءٌ فِي ٱلْأَرْضِ وَلَا فِي ٱلسَّمَاءِ وَهُوَ ٱلسَّمِيعُ ٱلْعَلِيمُ',
    transliteration: "Bismi-llāhi-lladhī lā yaḍurru maʿa-smihi shayʾun fi-l-arḍi wa lā fi-s-samāʾi wa huwa-s-samīʿu-l-ʿalīm",
    meaning: 'In the name of Allah, with Whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, All-Knowing.',
    benefits: 'Whoever says it 3 times in the morning and evening, nothing will harm him.',
    reference: 'Sunan Abu Dawood 5088, Jami at-Tirmidhi 3388',
    sourceBook: 'Abu Dawood',
    targetCount: 3,
    category: ['morning', 'evening', 'protection'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['morning-adhkar', 'evening-adhkar', 'protection', 'harm'],
    isSystem: true,
  },
  {
    id: 'radheetu-billahi',
    nameEn: 'Radheetu billahi Rabba',
    nameAr: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالإِسْلامِ دِينًا، وَبِمُحَمَّدٍ نَبِيًّا',
    transliteration: "Raḍītu bi-llāhi rabbā, wa bi-l-islāmi dīnā, wa bi-Muḥammadin nabiyyā",
    meaning: 'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad ﷺ as my Prophet.',
    benefits: 'Whoever says it 3 times in the morning and evening, it is a right upon Allah to please him on the Day of Judgement.',
    reference: 'Sunan Abu Dawood 5072, Jami at-Tirmidhi 3389',
    sourceBook: 'Abu Dawood',
    targetCount: 3,
    category: ['morning', 'evening', 'motivation'],
    time: 'morning',
    isFeatured: false,
    difficulty: 'medium',
    tags: ['morning-adhkar', 'evening-adhkar', 'iman', 'contentment'],
    isSystem: true,
  },
  {
    id: 'darood-ibrahim',
    nameEn: 'Darood Ibrahim',
    nameAr: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ',
    transliteration: "Allāhumma ṣalli ʿalā Muḥammad wa ʿalā āli Muḥammad, kamā ṣallayta ʿalā Ibrāhīm wa ʿalā āli Ibrāhīm, innaka ḥamīdun majīd. Allāhumma bārik ʿalā Muḥammad wa ʿalā āli Muḥammad, kamā bārakta ʿalā Ibrāhīm wa ʿalā āli Ibrāhīm, innaka ḥamīdun majīd",
    meaning: 'O Allah, send Your blessings upon Muhammad and the family of Muhammad, as You sent blessings upon Ibrahim and the family of Ibrahim. Verily You are Full of Praise, Full of Glory. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim. Verily You are Full of Praise, Full of Glory.',
    benefits: 'For every Salawat sent upon the Prophet ﷺ, Allah sends 10 blessings upon the person, erases 10 sins, and raises him 10 ranks.',
    reference: 'Sahih al-Bukhari 3370, Sahih Muslim 406',
    sourceBook: 'Sahih al-Bukhari',
    targetCount: 10,
    category: ['salawat', 'daily', 'morning', 'evening'],
    time: 'anytime',
    isFeatured: true,
    difficulty: 'long',
    tags: ['salawat', 'darood', 'prophet', 'blessings'],
    isSystem: true,
  },
  {
    id: 'lailahaillallah',
    nameEn: 'La ilaha illa Allah',
    nameAr: 'لَا إِلَٰهَ إِلَّا ٱللَّٰهُ',
    transliteration: 'Lā ilāha illa-llāh',
    meaning: 'There is no god but Allah',
    benefits: 'The best of dhikr. Renews faith. The Prophet ﷺ said: "Renew your faith" — meaning say La ilaha illa Allah.',
    reference: 'Musnad Ahmad, Hisnul Muslim',
    sourceBook: 'Hisnul Muslim',
    targetCount: 100,
    category: ['daily', 'morning', 'evening', 'motivation'],
    time: 'anytime',
    isFeatured: false,
    difficulty: 'easy',
    tags: ['tahlil', 'iman', 'faith'],
    isSystem: true,
  },
];

// Helper: get adhkaar by category
export const getAdhkaarByCategory = (category: string): Dhikr[] =>
  ADHKAAR_LIBRARY.filter((d) => d.category?.includes(category as never));

// Helper: get featured adhkaar
export const getFeaturedAdhkaar = (): Dhikr[] =>
  ADHKAAR_LIBRARY.filter((d) => d.isFeatured);

// Helper: get morning routine (ordered)
export const getMorningRoutine = (): Dhikr[] =>
  ADHKAAR_LIBRARY.filter((d) => d.category?.includes('morning')).slice(0, 6);

// Helper: get evening routine (ordered)
export const getEveningRoutine = (): Dhikr[] =>
  ADHKAAR_LIBRARY.filter((d) => d.category?.includes('evening')).slice(0, 6);

// ─── Default System Routines ────────────────────────────────────────────────

export const DEFAULT_ROUTINES: Routine[] = [
  {
    id: 'routine-morning',
    name: 'Morning Routine',
    emoji: '🌅',
    dhikrIds: [
      'astaghfirullah',
      'sayyidul-istighfar',
      'ayatul-kursi',
      'surah-ikhlas',
      'surah-falaq',
      'surah-naas',
      'subhanallah',
      'alhamdulillah',
      'allahuakbar',
      'darood-ibrahim',
    ],
    isSystem: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'routine-evening',
    name: 'Evening Routine',
    emoji: '🌙',
    dhikrIds: [
      'astaghfirullah',
      'ayatul-kursi',
      'surah-ikhlas',
      'surah-falaq',
      'surah-naas',
      'subhanallahi-wa-bihamdihi',
      'darood-ibrahim',
    ],
    isSystem: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'routine-after-salah',
    name: 'After Salah',
    emoji: '🤲',
    dhikrIds: [
      'subhanallah',
      'alhamdulillah',
      'allahuakbar',
      'ayatul-kursi',
      'darood-ibrahim',
    ],
    isSystem: true,
    createdAt: new Date(0).toISOString(),
  },
];
